### ISSUE TITLE
Request: Scala 3 support 

### ISSUE THREAD

**Issue by oltyant** [neotypes/neotypes#469]
When can neotypes support Scala 3?

**Comment by BalmungSan** [comment]
Hi @oltyant the plan was to first release a version supporting **CE3** and then **Scala 3**.
But **Monix** has kept us blocked with the first thing.

Anyways, I hope to find some time soon to give the **Scala 3** bit a go.

**Comment by oltyant** [comment]
Hi @BalmungSan , thanks for the quick answer!

**Comment by BalmungSan** [comment]
# Roadmap

- [x] Move `generic` to its own module and fix the tests - #548
- [ ] Add a **Scala 3** version of `generic` module - _(WIP)_ #555
- [ ] Add a **Scala 3** version of **cypher** string interpolator - _(WIP)_ #555
- [ ] Cross-compile all other modules _(this should work out of the box)_

**Comment by PerWiklander** [comment]
Any updates on this? Is it included in the upcoming 1.0 release?

**Comment by BalmungSan** [comment]
@PerWiklander hey, sorry, forgot to close this one. Actually the latest `RC` of **neotypes** fully supports **Scala 3**, this was released almost a year ago.

I haven't made a `1.0.0` proper release because I wanted to change the way the `sc` string interpolator worked, but I haven't found the time nor the motivation to do it.

Just use the latest `RC`, is pretty stable and I probably will just promote that one as final `1.0.0` this weekend.

**Comment by BalmungSan** [comment]
https://github.com/neotypes/neotypes/releases/tag/v1.0.0
